name: Build and release on GitHub

on:
  push:
    branches:
      - main

jobs:
  check-release:
    name: "Check if there is a need for a new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Semantic Release - dry run for getting version
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    outputs:
      tag: ${{ steps.semantic.outputs.new_release_version }}

  tests:
    name: Build and release
    runs-on: windows-latest
    needs: check-release
    if: ${{ contains(needs.check-release.outputs.tag, '.') }}
    env:
      NEW_RELEASE_VERSION: ${{needs.check-release.outputs.tag}}

    steps:
      - uses: actions/checkout@v4

      - name: Build React project
        run: |
          cd ./ironbug-viewer
          npm i
          npm run build

      - name: Compile viewer
        run: |
          dotnet build ./Ironbug.Viewer.GH/Ironbug.Viewer.GH.csproj --configuration Release -f net48 /p:Version=${{ env.NEW_RELEASE_VERSION }} -o ./IbViewer /restore

      - name: Zip assets
        run: |
          cp ./ironbug-viewer/dist/* ./IbViewer/wwwroot/ -R
          ls ./IbViewer -r
          7z a -tzip IbViewer-${{ env.NEW_RELEASE_VERSION }}.zip ./IbViewer/

      - name: Upload asset
        uses: actions/upload-artifact@v4
        with:
          name: IbViewer
          path: |
            IbViewer-${{ env.NEW_RELEASE_VERSION }}.zip

  Release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    needs: [tests]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        run: |
          cp ./IbViewer/IbViewer-*.zip ./
          ls

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
