name: Build and release on GitHub

on:
  push:
    branches:
      - main

jobs:
  check-release:
    name: "Check if there is a need for a new release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Semantic Release - dry run for getting version
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    outputs:
      tag: ${{ steps.semantic.outputs.new_release_version }}

  tests:
    name: "Run tests"
    runs-on: windows-latest
    needs: check-release
    if: ${{ contains(needs.check-release.outputs.tag, '.') }}
    continue-on-error: false
    strategy:
      fail-fast: true
      matrix:
        dotnet_version: ["net48", "net7.0-windows"]
    env:
      NEW_RELEASE_VERSION: ${{needs.check-release.outputs.tag}}
      LBT_FOLDER: "C:/Program Files/ladybug_tools"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Build React project
        run: |
          cd ./ironbug-viewer
          npm i
          npm run build

      - name: Compile viewer
        run: |
          dotnet build ./Ironbug.Viewer.GH/Ironbug.Viewer.GH.csproj --configuration Release -f net48 /p:Version=${{ env.NEW_RELEASE_VERSION }} -o ./IbViewer /restore

      - name: Zip assets
        run: |
          cp ./ironbug-viewer/dist/* ./IbViewer/wwwroot/ -R
          ls ./IbViewer -r
          7z a -tzip IbViewer-${{ env.NEW_RELEASE_VERSION }}.zip ./IbViewer/

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
